[project]
name = "SYS3062SetupPackage"
version = "2025.12.26"
description = "This is a package to be used with UV!"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
	"numpy",
	"statsmodels",
	"scipy",
	"matplotlib",
	"seaborn",
	"pymc",
	"arviz",
	"pytensor",
	"simpy",
	"salabim",
	"mesa",
	"ciw",
	"distfit",
	"salib",
]
